# Development/Testing Docker Compose Configuration
# Uses /tmp for ephemeral storage
# External port: 64181:80 (random unused port in 64xxx range)

services:
  gitignore:
    image: gitignore:dev
    container_name: gitignore-test
    restart: "no"

    environment:
      - CONFIG_DIR=/config
      - DATA_DIR=/data
      - LOGS_DIR=/logs
      - PORT=80
      - ADDRESS=0.0.0.0
      - DB_PATH=/data/db/gitignore.db
      - ADMIN_USER=administrator
      - ADMIN_PASSWORD=testpass123
      - DEV=true

    volumes:
      - /tmp/gitignore/rootfs/config/gitignore:/config
      - /tmp/gitignore/rootfs/data/gitignore:/data
      - /tmp/gitignore/rootfs/logs/gitignore:/logs

    ports:
      - "64181:80"

    networks:
      - gitignore

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Optional: PostgreSQL for testing
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: gitignore-postgres-test
  #   restart: "no"
  #
  #   environment:
  #     POSTGRES_DB: gitignore_test
  #     POSTGRES_USER: gitignore
  #     POSTGRES_PASSWORD: testpass
  #
  #   volumes:
  #     - /tmp/gitignore/rootfs/db/postgres:/var/lib/postgresql/data
  #
  #   networks:
  #     - gitignore

networks:
  gitignore:
    name: gitignore
    external: false
    driver: bridge
