// Package tor implements the built-in Tor hidden service (AI.md PART 31).
//
// The server binary fully owns a dedicated external tor process via
// github.com/cretz/bine, keeping CGO_ENABLED=0 static builds intact. The hidden
// service maps .onion:{virtual_port} to 127.0.0.1:{server_port} using the
// control ADD_ONION command (not a torrc HiddenServiceDir), and the ed25519
// secret key is persisted so the .onion address is stable across restarts.
//
// Tor is optional: a missing binary is logged at INFO and the server continues
// without Tor. All operations are best-effort and never block server startup.
package tor

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sync"
	"time"

	"github.com/cretz/bine/control"
	"github.com/cretz/bine/tor"

	"github.com/apimgr/gitignore/src/config"
)

// TorService manages a running Tor hidden service and optional outbound dialer.
// The server binary fully owns and controls the Tor process lifecycle.
type TorService struct {
	tor *tor.Tor
	// serviceID is the .onion address without the ".onion" suffix.
	serviceID string
	// key is the ed25519 key backing the persistent address (nil when Tor
	// generated a fresh key that was then saved to disk).
	key control.Key
	// serverPort is the server's HTTP port that the hidden service forwards to.
	serverPort int
	// dialer routes outbound connections through Tor (nil when disabled).
	dialer *tor.Dialer
}

// OnionAddress returns the full .onion address.
func (s *TorService) OnionAddress() string {
	return s.serviceID + ".onion"
}

// OutboundEnabled reports whether Tor outbound connections are available.
func (s *TorService) OutboundEnabled() bool {
	return s.dialer != nil
}

// GetHTTPClient returns an HTTP client, optionally routed through Tor. When
// useTor is false or no dialer is configured, a direct client is returned.
func (s *TorService) GetHTTPClient(useTor bool) *http.Client {
	if !useTor || s.dialer == nil {
		return &http.Client{Timeout: 30 * time.Second}
	}
	return &http.Client{
		Timeout: 60 * time.Second,
		Transport: &http.Transport{
			DialContext: s.dialer.DialContext,
		},
	}
}

// Close shuts down the Tor process.
func (s *TorService) Close() error {
	if s.tor != nil {
		return s.tor.Close()
	}
	return nil
}

// commonTorPaths lists well-known tor binary locations checked after PATH.
func commonTorPaths() []string {
	switch runtime.GOOS {
	case "windows":
		return []string{`C:\Program Files\Tor\tor.exe`, `C:\Program Files (x86)\Tor\tor.exe`}
	case "darwin":
		return []string{"/usr/local/bin/tor", "/opt/homebrew/bin/tor"}
	default:
		return []string{"/usr/bin/tor", "/usr/local/bin/tor", "/bin/tor"}
	}
}

// FindBinary resolves the tor executable. It checks the configured path first,
// then PATH, then common install locations. The second return value reports
// whether a usable binary was found.
func FindBinary(configured string) (string, bool) {
	if configured != "" {
		if _, err := os.Stat(configured); err == nil {
			return configured, true
		}
		return "", false
	}
	if p, err := exec.LookPath("tor"); err == nil {
		return p, true
	}
	for _, p := range commonTorPaths() {
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

// getTorConfig generates torrc content from Tor settings (AI.md PART 31). The
// hidden service itself is created via control.AddOnion, not torrc; this only
// configures the tor daemon. All ports use runtime "auto" detection and never
// the default tor ports (9050/9051).
func getTorConfig(cfg *config.TorConfig) string {
	controlConfig := "ControlPort 127.0.0.1:auto"

	socksConfig := "SocksPort 0"
	if cfg.UseNetwork {
		socksConfig = "SocksPort auto"
	}

	safeLogging := "1"
	if !cfg.SafeLogging {
		safeLogging = "0"
	}

	var accountingConfig string
	if cfg.MaxMonthlyBandwidth != "" && cfg.MaxMonthlyBandwidth != "unlimited" {
		accountingConfig = fmt.Sprintf(`
# Monthly bandwidth limit
AccountingStart month 1 00:00
AccountingMax %s`, cfg.MaxMonthlyBandwidth)
	}

	return fmt.Sprintf(`
# ============================================================
# Tor Configuration - Generated by server binary
# This file is PERSISTENT - it is not regenerated on normal startup
# Manual edits may be overwritten when config is saved via operator
# ============================================================

# SOCKS port for outbound connections (0 = disabled, auto = runtime port)
# Never uses the default SOCKS port - runtime detection only
%s

# Control connection
# Never uses the default control port - uses a runtime localhost port on all OSes
%s

# Security Hardening
SafeLogging %s

# Circuit limits
MaxCircuitDirtiness 600

# Bandwidth limits per second (from config)
BandwidthRate %s
BandwidthBurst %s
%s

# Disable unused features - not a relay or exit
ExitRelay 0
ExitPolicy reject *:*
ORPort 0
DirPort 0

# Hidden service optimizations (actual HS created via ADD_ONION)
HiddenServiceSingleHopMode 0

# Faster startup
FetchDirInfoEarly 1
FetchDirInfoExtraEarly 1

# Reduce memory usage
DisableDebuggerAttachment 1
`, socksConfig, controlConfig, safeLogging, cfg.BandwidthRate, cfg.BandwidthBurst, accountingConfig)
}

// ensureTorDirs creates the Tor directories with 0700 permissions and enforces
// ownership. configDir holds the torrc; dataDir holds runtime data and keys.
func ensureTorDirs(configDir, dataDir string) error {
	dirs := []string{
		filepath.Join(configDir, "tor"),
		filepath.Join(dataDir, "tor"),
		filepath.Join(dataDir, "tor", "site"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0700); err != nil {
			return fmt.Errorf("create tor dir %s: %w", dir, err)
		}
		if err := os.Chmod(dir, 0700); err != nil {
			return fmt.Errorf("chmod tor dir %s: %w", dir, err)
		}
		if runtime.GOOS != "windows" {
			if err := os.Chown(dir, os.Getuid(), os.Getgid()); err != nil {
				return fmt.Errorf("chown tor dir %s: %w", dir, err)
			}
		}
	}
	return nil
}

// ensureTorrc creates torrc only if it does not already exist. It returns true
// when the file was newly created. Existing files are preserved (permissions
// are re-enforced).
func ensureTorrc(path string, content []byte) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return false, fmt.Errorf("create parent dir: %w", err)
	}

	if _, err := os.Stat(path); err == nil {
		if err := os.Chmod(path, 0600); err != nil {
			return false, fmt.Errorf("chmod file: %w", err)
		}
		return false, nil
	}

	if err := os.WriteFile(path, content, 0600); err != nil {
		return false, fmt.Errorf("write file: %w", err)
	}
	if runtime.GOOS != "windows" {
		if err := os.Chown(path, os.Getuid(), os.Getgid()); err != nil {
			return false, fmt.Errorf("chown file: %w", err)
		}
	}
	return true, nil
}

// updateTorrc overwrites torrc with new content for operator-driven config
// changes.
func updateTorrc(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("create parent dir: %w", err)
	}
	if err := os.WriteFile(path, content, 0600); err != nil {
		return fmt.Errorf("write file: %w", err)
	}
	if err := os.Chmod(path, 0600); err != nil {
		return fmt.Errorf("chmod file: %w", err)
	}
	if runtime.GOOS != "windows" {
		if err := os.Chown(path, os.Getuid(), os.Getgid()); err != nil {
			return fmt.Errorf("chown file: %w", err)
		}
	}
	return nil
}

// ensureTorFile writes a generic Tor file (keys, hostname) with 0600
// permissions, overwriting any existing content.
func ensureTorFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("create parent dir: %w", err)
	}
	if err := os.WriteFile(path, content, 0600); err != nil {
		return fmt.Errorf("write file: %w", err)
	}
	if err := os.Chmod(path, 0600); err != nil {
		return fmt.Errorf("chmod file: %w", err)
	}
	if runtime.GOOS != "windows" {
		if err := os.Chown(path, os.Getuid(), os.Getgid()); err != nil {
			return fmt.Errorf("chown file: %w", err)
		}
	}
	return nil
}

// saveOnionKey persists the ed25519 secret key blob so the .onion address is
// stable across restarts. The blob is the base64 form returned by bine.
func saveOnionKey(path string, key control.Key) error {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(key.Blob()), 0600)
}

// loadOnionKey reads a persisted ed25519 secret key blob and reconstructs a
// control.Key. It returns (nil, nil) when no key file exists yet.
func loadOnionKey(path string) (control.Key, error) {
	blob, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	if len(blob) == 0 {
		return nil, nil
	}
	return control.ED25519KeyFromBlob(string(blob))
}

// startDedicatedTor starts a dedicated tor process owned by this server and
// creates the hidden service forwarding .onion:{virtual_port} to
// 127.0.0.1:serverPort. The HTTP listener on serverPort must already be
// running. configDir and dataDir are passed explicitly (paths are derived by
// the caller) because Tor directories are always under the app's directories.
func startDedicatedTor(ctx context.Context, serverPort int, configDir, dataDir string, cfg *config.TorConfig) (*TorService, error) {
	if err := ensureTorDirs(configDir, dataDir); err != nil {
		return nil, fmt.Errorf("failed to create tor directories: %w", err)
	}

	torrcPath := filepath.Join(configDir, "tor", "torrc")
	torDataDir := filepath.Join(dataDir, "tor")
	keyPath := filepath.Join(dataDir, "tor", "site", "hs_ed25519_secret_key")
	hostnamePath := filepath.Join(dataDir, "tor", "site", "hostname")

	created, err := ensureTorrc(torrcPath, []byte(getTorConfig(cfg)))
	if err != nil {
		return nil, fmt.Errorf("failed to ensure torrc: %w", err)
	}
	if created {
		log.Printf("Created new torrc at %s", torrcPath)
	}

	conf := &tor.StartConf{
		TorrcFile:       torrcPath,
		DataDir:         torDataDir,
		NoAutoSocksPort: true,
	}
	if cfg.Binary != "" {
		conf.ExePath = cfg.Binary
	}

	t, err := tor.Start(ctx, conf)
	if err != nil {
		return nil, fmt.Errorf("failed to start dedicated tor: %w", err)
	}

	bootstrapTimeout := time.Duration(cfg.BootstrapTimeout) * time.Second
	dialCtx, cancel := context.WithTimeout(ctx, bootstrapTimeout)
	defer cancel()
	if err := t.EnableNetwork(dialCtx, true); err != nil {
		t.Close()
		return nil, fmt.Errorf("failed to enable tor network: %w", err)
	}

	existingKey, err := loadOnionKey(keyPath)
	if err != nil {
		t.Close()
		return nil, fmt.Errorf("failed to load existing key: %w", err)
	}

	req := &control.AddOnionRequest{
		Ports: []*control.KeyVal{
			control.NewKeyVal(fmt.Sprintf("%d", cfg.VirtualPort), fmt.Sprintf("127.0.0.1:%d", serverPort)),
		},
	}
	if existingKey != nil {
		req.Key = existingKey
	} else {
		req.Key = control.GenKey(control.KeyAlgoED25519V3)
	}
	if cfg.MaxStreamsPerCircuit > 0 {
		req.MaxStreams = cfg.MaxStreamsPerCircuit
	}

	resp, err := t.Control.AddOnion(req)
	if err != nil {
		t.Close()
		return nil, fmt.Errorf("failed to create onion service: %w", err)
	}

	if existingKey == nil && resp.Key != nil {
		if err := saveOnionKey(keyPath, resp.Key); err != nil {
			log.Printf("Warning: failed to save onion key: %v", err)
		}
	}

	// Persist the hostname so out-of-process CLI commands (tor status) can read
	// the current address; ADD_ONION does not write a hostname file itself.
	if err := ensureTorFile(hostnamePath, []byte(resp.ServiceID+".onion\n")); err != nil {
		log.Printf("Warning: failed to write tor hostname file: %v", err)
	}

	svc := &TorService{
		tor:        t,
		serviceID:  resp.ServiceID,
		key:        existingKey,
		serverPort: serverPort,
	}

	if cfg.UseNetwork {
		dialer, err := t.Dialer(ctx, nil)
		if err != nil {
			log.Printf("Warning: failed to create Tor dialer: %v", err)
		} else {
			svc.dialer = dialer
			log.Printf("Tor outbound connections enabled")
		}
	}

	log.Printf("Tor hidden service started: %s.onion:%d -> 127.0.0.1:%d", resp.ServiceID, cfg.VirtualPort, serverPort)
	return svc, nil
}

// TorManager owns the Tor process lifecycle: start, restart, config updates,
// address regeneration, key import, and shutdown. It is safe for concurrent
// use.
type TorManager struct {
	mu         sync.Mutex
	service    *TorService
	config     *config.TorConfig
	configDir  string
	dataDir    string
	serverPort int
	ctx        context.Context
	cancel     context.CancelFunc
}

// NewTorManager creates a Tor manager. serverPort is the server's HTTP port the
// hidden service forwards to; configDir and dataDir locate the Tor files.
func NewTorManager(ctx context.Context, serverPort int, configDir, dataDir string, cfg *config.TorConfig) *TorManager {
	mctx, cancel := context.WithCancel(ctx)
	return &TorManager{
		config:     cfg,
		configDir:  configDir,
		dataDir:    dataDir,
		serverPort: serverPort,
		ctx:        mctx,
		cancel:     cancel,
	}
}

// Start initializes Tor. Callers should treat a returned error as non-fatal:
// the server continues without Tor.
func (tm *TorManager) Start() error {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	return tm.startLocked()
}

// startLocked starts Tor; the caller must hold tm.mu.
func (tm *TorManager) startLocked() error {
	service, err := startDedicatedTor(tm.ctx, tm.serverPort, tm.configDir, tm.dataDir, tm.config)
	if err != nil {
		return err
	}
	tm.service = service
	return nil
}

// Restart stops and starts Tor with the current config.
func (tm *TorManager) Restart() error {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}
	return tm.startLocked()
}

// UpdateConfig regenerates torrc from cfg and restarts Tor.
func (tm *TorManager) UpdateConfig(cfg *config.TorConfig) error {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	tm.config = cfg
	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}

	torrcPath := filepath.Join(tm.configDir, "tor", "torrc")
	if err := updateTorrc(torrcPath, []byte(getTorConfig(cfg))); err != nil {
		return fmt.Errorf("failed to update torrc: %w", err)
	}
	return tm.startLocked()
}

// RegenerateAddress deletes the persisted keys and starts Tor with a fresh
// random .onion address.
func (tm *TorManager) RegenerateAddress() (string, error) {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}

	keysDir := filepath.Join(tm.dataDir, "tor", "site")
	if err := os.RemoveAll(keysDir); err != nil {
		return "", fmt.Errorf("failed to remove old keys: %w", err)
	}

	if err := tm.startLocked(); err != nil {
		return "", err
	}
	return tm.service.OnionAddress(), nil
}

// ApplyKeys replaces the persisted secret key blob and restarts Tor. The blob
// is the base64 ed25519 form produced by ExportKey / bine's Key.Blob().
func (tm *TorManager) ApplyKeys(privateKey []byte) (string, error) {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	if tm.service != nil {
		tm.service.Close()
		tm.service = nil
	}

	keyPath := filepath.Join(tm.dataDir, "tor", "site", "hs_ed25519_secret_key")
	if err := ensureTorFile(keyPath, privateKey); err != nil {
		return "", fmt.Errorf("failed to write key: %w", err)
	}

	if err := tm.startLocked(); err != nil {
		return "", err
	}
	return tm.service.OnionAddress(), nil
}

// Close shuts down the Tor process and cancels the manager context.
func (tm *TorManager) Close() error {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	if tm.cancel != nil {
		tm.cancel()
	}
	if tm.service != nil {
		err := tm.service.Close()
		tm.service = nil
		return err
	}
	return nil
}

// OnionAddress returns the current .onion address, or "" when Tor is not
// running.
func (tm *TorManager) OnionAddress() string {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		return tm.service.OnionAddress()
	}
	return ""
}

// GetHTTPClient returns an HTTP client, optionally routed through Tor. It falls
// back to a direct client when Tor is not running.
func (tm *TorManager) GetHTTPClient(useTor bool) *http.Client {
	tm.mu.Lock()
	defer tm.mu.Unlock()
	if tm.service != nil {
		return tm.service.GetHTTPClient(useTor)
	}
	return &http.Client{Timeout: 30 * time.Second}
}

// Monitor watches the running Tor process and restarts it via the manager when
// the control connection becomes unresponsive. It returns when ctx is done.
func (tm *TorManager) Monitor(ctx context.Context) {
	ticker := time.NewTicker(30 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			tm.mu.Lock()
			svc := tm.service
			tm.mu.Unlock()
			if svc == nil || svc.tor == nil {
				continue
			}
			if _, err := svc.tor.Control.GetInfo("version"); err != nil {
				log.Printf("Tor: connection lost, reconnecting: %v", err)
				if err := tm.Restart(); err != nil {
					log.Printf("Tor: restart failed: %v", err)
				}
			}
		}
	}
}
